services:
  - type: web
    name: calendario-ai-smart
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
